
name: CI

on:
  push:
    paths:
      - '**/*.java'

  pull_request:

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build
        run: |
          mvn clean install

      - name: Upload Standalone jar
        uses: actions/upload-artifact@v2
        with:
          name: EnderPearlPlus-Standalone.jar
          path: target/EnderPearlPlus-*.jar

      - name: Upload Light jar
        uses: actions/upload-artifact@v2
        with:
            name: EnderPearlPlus-Light.jar
            path: target/original-EnderPearlPlus-*.jar
